// <auto-generated />
using ApiMicrosservicesProduct.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMicrosservicesProduct.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240110035741_FirstTable")]
    partial class FirstTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_menu_kerwinfrost_160x160-1:menu-category?resmode=sharp2",
                            Name = "The Kerwin Frost Box"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_mcnuggetscombo_160x160:menu-category?resmode=sharp2",
                            Name = "McNuggets® and Meals"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/desserts_shakes_300x300:menu-category?resmode=sharp2",
                            Name = "Sweets & Treats"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/breakfast_300x300:menu-category?resmode=sharp2",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/snacks_sides_300x300:menu-category?resmode=sharp2",
                            Name = "Fries® & Slides"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/drinks_300x300:menu-category?resmode=sharp2",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/burgers_300x300:menu-category?resmode=sharp2",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_happy_meal_160x160:menu-category?resmode=sharp2",
                            Name = "Happy Meal®"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/D123_160x160:menu-category?resmode=sharp2",
                            Name = "$1 $2 $3 Dollar Menu*"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_chickenfishsandwiches_160x160:menu-category?resmode=sharp2",
                            Name = "Chicken & Fish Sandwiches"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/mccafe_300x300:menu-category?resmode=sharp2",
                            Name = "McCafé® Coffees"
                        });
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ever wondered what's on a Big Mac®? The McDonald's Big Mac® is a 100% beef burger with a taste like no other. The mouthwatering perfection starts with two 100% pure all beef patties and Big Mac® sauce sandwiched between a sesame seed bun. It’s topped off with pickles, crisp shredded lettuce, finely chopped onion, and a slice of American cheese. It contains no artificial flavors, preservatives, or added colors from artificial sources. Our pickle contains an artificial preservative, so skip it if you like.",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/Header_BigMac_832x472:product-header-desktop?wid=830\\u0026hei=456\\u0026dpr=off\",\"https://s7d1.scene7.com/is/image/mcdonalds/big_mac_bun\",\"https://s7d1.scene7.com/is/image/mcdonalds/10_1_patty\",\"https://s7d1.scene7.com/is/image/mcdonalds/shredded_lettuce\",\"https://s7d1.scene7.com/is/image/mcdonalds/BigMacSauce_180x180\",\"https://s7d1.scene7.com/is/image/mcdonalds/ingredient_american_cheese_180x180\",\"https://s7d1.scene7.com/is/image/mcdonalds/pickles\",\"https://s7d1.scene7.com/is/image/mcdonalds/reconstituted_onions\"]",
                            Name = "Big Mac®",
                            Price = 15.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Our tender, juicy Chicken McNuggets® are made with all white meat chicken and no artificial colors, flavors or preservatives. There are 410 calories in a 10 piece Chicken McNuggets®. Pair them with your favorite dipping sauces when you Mobile Order & Pay!*",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/DC_202208_5280_10McNuggets_Stacked_832x472:product-header-desktop?wid=830\\u0026hei=458\\u0026dpr=off\"]",
                            Name = "10 Piece Chicken McNuggets®",
                            Price = 25.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "The McDonald’s McFlurry® with OREO® Cookies is a popular combination of creamy vanilla soft serve with crunchy pieces of OREO® cookies!  There are 510 calories in a regular size OREO® McFlurry® at McDonald's. Check out all the McFlurry® flavors on the McDonald's Desserts & Shakes menu. Order a McFlurry® with OREO® Cookies using Mobile Order & Pay* in the McDonald’s app.",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/DC_202002_3832_OREOMcFlurry_832x472:product-header-desktop?wid=830\\u0026hei=458\\u0026dpr=off\"]",
                            Name = "McFlurry® with OREO® Cookies",
                            Price = 5.99m,
                            Stock = 2
                        });
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Product", b =>
                {
                    b.HasOne("ApiMicrosservicesProduct.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
