// <auto-generated />
using ApiMicrosservicesProduct.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMicrosservicesProduct.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_menu_kerwinfrost_160x160-1:menu-category?resmode=sharp2",
                            Name = "The Kerwin Frost Box"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_mcnuggetscombo_160x160:menu-category?resmode=sharp2",
                            Name = "McNuggets® and Meals"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/desserts_shakes_300x300:menu-category?resmode=sharp2",
                            Name = "Sweets & Treats"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/breakfast_300x300:menu-category?resmode=sharp2",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/snacks_sides_300x300:menu-category?resmode=sharp2",
                            Name = "Fries® & Slides"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/drinks_300x300:menu-category?resmode=sharp2",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/burgers_300x300:menu-category?resmode=sharp2",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_happy_meal_160x160:menu-category?resmode=sharp2",
                            Name = "Happy Meal®"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/D123_160x160:menu-category?resmode=sharp2",
                            Name = "$1 $2 $3 Dollar Menu*"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/nav_chickenfishsandwiches_160x160:menu-category?resmode=sharp2",
                            Name = "Chicken & Fish Sandwiches"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://s7d1.scene7.com/is/image/mcdonalds/mccafe_300x300:menu-category?resmode=sharp2",
                            Name = "McCafé® Coffees"
                        });
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The McDonald's 10 piece Chicken McNuggets® Combo Meal you love, now inside designer packaging, plus a McNugget Buddy collectible outfitted by Kerwin Frost. Featuring 10 tender and delicious Chicken McNuggets® made with all white meat chicken—plus our World Famous Fries® and your choice of a medium McDonald’s drink, There are 940 calories in a Chicken McNuggets® Combo Meal with a medium Coca-Cola® and medium Fries. Sauces each add 30-110 calories.",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/Header_Menu_KerwinFrost_10Nuggetsv3_832x472:product-header-desktop?wid=830\\u0026hei=456\\u0026dpr=off\"]",
                            Name = "The Kerwin Frost Box 10 piece Chicken McNuggets® Meal",
                            Price = 69.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "The McDonald's Bacon, Egg & Cheese Biscuit breakfast sandwich features a warm, buttermilk biscuit brushed with real butter, thick cut Applewood smoked bacon, a fluffy folded egg, and a slice of melty American cheese. There are 460 calories in a Bacon, Egg & Cheese Biscuit at McDonald's. Try one today with a Premium Roast Coffee and order with Mobile Order & Pay on the McDonald's App!",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/DC_202211_0085_BaconEggCheeseBiscuit_832x472:product-header-desktop?wid=830\\u0026hei=458\\u0026dpr=off\",\"https://s7d1.scene7.com/is/image/mcdonalds/biscuit_ingredient\",\"https://s7d1.scene7.com/is/image/mcdonalds/folded_egg\",\"https://s7d1.scene7.com/is/image/mcdonalds/ingredient_american_cheese_180x180\",\"https://s7d1.scene7.com/is/image/mcdonalds/applewood_bacon\",\"https://s7d1.scene7.com/is/image/mcdonalds/butter_salted\",\"https://s7d1.scene7.com/is/image/mcdonalds/clarified_butter\"]",
                            Name = "Bacon, Egg & Cheese Biscuit",
                            Price = 15.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Ever wondered what's on a Big Mac®? The McDonald's Big Mac® is a 100% beef burger with a taste like no other. The mouthwatering perfection starts with two 100% pure all beef patties and Big Mac® sauce sandwiched between a sesame seed bun. It’s topped off with pickles, crisp shredded lettuce, finely chopped onion, and a slice of American cheese. It contains no artificial flavors, preservatives, or added colors from artificial sources. Our pickle contains an artificial preservative, so skip it if you like.",
                            Images = "[\"https://s7d1.scene7.com/is/image/mcdonalds/Header_BigMac_832x472:product-header-desktop?wid=830\\u0026hei=456\\u0026dpr=off\",\"https://s7d1.scene7.com/is/image/mcdonalds/big_mac_bun\",\"https://s7d1.scene7.com/is/image/mcdonalds/10_1_patty\",\"https://s7d1.scene7.com/is/image/mcdonalds/shredded_lettuce\",\"https://s7d1.scene7.com/is/image/mcdonalds/BigMacSauce_180x180\",\"https://s7d1.scene7.com/is/image/mcdonalds/ingredient_american_cheese_180x180\",\"https://s7d1.scene7.com/is/image/mcdonalds/pickles\",\"https://s7d1.scene7.com/is/image/mcdonalds/reconstituted_onions\"]",
                            Name = "Big Mac®",
                            Price = 5.99m,
                            Stock = 85
                        });
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Product", b =>
                {
                    b.HasOne("ApiMicrosservicesProduct.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApiMicrosservicesProduct.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
